<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Jogos Formulário envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'recriaJogos@outlook.com',
		'to' => 'recriaJogos@outlook.com'
	),
	'fields' => array(
		'custom_U9216' => array(
			'order' => 1,
			'type' => 'string',
			'label' => ' Título do jogo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \" Título do jogo\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Objetivo (Pais)',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Objetivo (Pais)\" é obrigatório.',
				'format' => 'O campo \"Objetivo (Pais)\" possui um email inválido.'
			)
		),
		'custom_U9221' => array(
			'order' => 2,
			'type' => 'string',
			'label' => ' Descrição',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \" Descrição\" é obrigatório.'
			)
		),
		'custom_U12755' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Url do Jogo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Url do Jogo\" é obrigatório.'
			)
		),
		'custom_U12765' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Url da Demo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Url da Demo\" é obrigatório.'
			)
		),
		'custom_U10770' => array(
			'order' => 4,
			'type' => 'radiogroup',
			'label' => ' Idade focada',
			'required' => true,
			'optionItems' => array(
				'2 aos 3 anos',
				'4 aos 5 anos',
				'6 aos 7 anos',
				'8 aos 10 anos'
			),
			'errors' => array(
				'required' => 'O campo \" Idade focada\" é obrigatório.',
				'format' => 'O campo \" Idade focada\" possui um valor inválido.'
			)
		)
	)
);

process_form($form);
?>
